name: README link check
on:
  push:
    paths: ["README.md","index.html","docs/**"]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress README.md index.html docs
